using UnityEngine;
using System.Collections;

public class GrenadeExplode : MonoBehaviour {
	public float delay = 3;	//time, in seconds, before grenade explodes
	public float radius = 3;	//blast radius
	public float explosionForce = 3;	//amount of force generated by blast

	void Start () {
		StartCoroutine(Explode());	//explode following a delay
	}

	IEnumerator Explode(){
		yield return new WaitForSeconds(delay); //wait for delay
		//this will return all of the colliders within a certain radius
		Collider[] hits = Physics.OverlapSphere(transform.position, radius);
		//loops through the hits, assigning each in turn to a different variable called 'hit'
		foreach(Collider hit in hits){
			//filter out objects without rigidbodies
			if((hit.rigidbody) && (hit.rigidbody.tag != "Projectile")){
				//apply explosion-style force to each rigidbody
				hit.rigidbody.AddExplosionForce(explosionForce*50f, transform.position, radius*10f, 0, ForceMode.Impulse);
			} else if(hit.collider.tag == "Enemy"){		//if the collider is an enemy pushes it back
				hit.collider.SendMessage("Pushback", explosionForce, SendMessageOptions.DontRequireReceiver);
				hit.collider.SendMessage("OnHit", 1, SendMessageOptions.DontRequireReceiver);
			}
		}
		Destroy(gameObject); //destroy the grenade
	}
}
